;;(defvar buffer-to-move-to-another-window);; (current-buffer))
;;(setq buffer-to-move-to-another-window (current-buffer))
(defun get-this-buffer-to-move ()
  (interactive)
  ;;(setq buffer-to-move-to-another-window (current-buffer))
  (kill-new (buffer-name))
  (previous-buffer)
  (message (concat "buffer set to move: " (buffer-name)))
  )

(defun switch-to-buffer-to-move ()
  (interactive)
  (setq buffer-name-to-move-to (current-kill 0))
  (message buffer-name-to-move-to)
  (switch-to-buffer buffer-name-to-move-to)
  )
